name: ci

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - uses: actions/checkout@v2

    - name: Format Code
      run: go fmt -x -mod=vendor ./...
    
    - name: Go Vet
      run: go vet -x -mod=vendor ./...

  unit-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit tests
        run: go test -v -count=1 --race --cover --short ./...
